// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'

export type AdminDeleteChatMessage = {
  entityId: bigint
}

/**
 * A namespace for generated helper functions.
 */
export namespace AdminDeleteChatMessage {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: AdminDeleteChatMessage
  ): void {
    AdminDeleteChatMessage.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): AdminDeleteChatMessage {
    return AdminDeleteChatMessage.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
