// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, Identity, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { HubItemType as __HubItemType } from './hub_item_type_type'

export type AdminUpdateGrantedHubItemState = {
  identity: Identity
  itemType: __HubItemType
  itemId: number
  balance: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace AdminUpdateGrantedHubItemState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('identity', AlgebraicType.createIdentityType()),
      new ProductTypeElement('itemType', __HubItemType.getTypeScriptAlgebraicType()),
      new ProductTypeElement('itemId', AlgebraicType.createI32Type()),
      new ProductTypeElement('balance', AlgebraicType.createU32Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: AdminUpdateGrantedHubItemState): void {
    AdminUpdateGrantedHubItemState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): AdminUpdateGrantedHubItemState {
    return AdminUpdateGrantedHubItemState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
