// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { BiomeDesc } from './biome_desc_type'

/**
 * Table handle for the table `biome_desc`.
 *
 * Obtain a handle from the [`biomeDesc`] property on [`RemoteTables`],
 * like `ctx.db.biomeDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.biomeDesc.on_insert(...)`.
 */
export class BiomeDescTableHandle {
  tableCache: TableCache<BiomeDesc>

  constructor(tableCache: TableCache<BiomeDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<BiomeDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `biomeType` unique index on the table `biome_desc`,
   * which allows point queries on the field of the same name
   * via the [`BiomeDescBiomeTypeUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.biomeDesc.biomeType().find(...)`.
   *
   * Get a handle on the `biomeType` unique index on the table `biome_desc`.
   */
  biomeType = {
    // Find the subscribed row whose `biomeType` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): BiomeDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.biomeType, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: BiomeDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: BiomeDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: BiomeDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: BiomeDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (ctx: EventContext, oldRow: BiomeDesc, newRow: BiomeDesc) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (ctx: EventContext, onRow: BiomeDesc, newRow: BiomeDesc) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
