// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { BuildingSetSignTextRequest as __BuildingSetSignTextRequest } from './building_set_sign_text_request_type'

export type BuildingSetSignText = {
  request: __BuildingSetSignTextRequest
}

/**
 * A namespace for generated helper functions.
 */
export namespace BuildingSetSignText {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('request', __BuildingSetSignTextRequest.getTypeScriptAlgebraicType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: BuildingSetSignText): void {
    BuildingSetSignText.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): BuildingSetSignText {
    return BuildingSetSignText.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
