// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { BuildingClaimDesc } from './building_claim_desc_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `building_claim_desc`.
 *
 * Obtain a handle from the [`buildingClaimDesc`] property on [`RemoteTables`],
 * like `ctx.db.buildingClaimDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.buildingClaimDesc.on_insert(...)`.
 */
export class BuildingClaimDescTableHandle {
  tableCache: TableCache<BuildingClaimDesc>

  constructor(tableCache: TableCache<BuildingClaimDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<BuildingClaimDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `buildingId` unique index on the table `building_claim_desc`,
   * which allows point queries on the field of the same name
   * via the [`BuildingClaimDescBuildingIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.buildingClaimDesc.buildingId().find(...)`.
   *
   * Get a handle on the `buildingId` unique index on the table `building_claim_desc`.
   */
  buildingId = {
    // Find the subscribed row whose `buildingId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): BuildingClaimDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.buildingId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: BuildingClaimDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: BuildingClaimDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: BuildingClaimDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: BuildingClaimDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: BuildingClaimDesc, newRow: BuildingClaimDesc) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: BuildingClaimDesc, newRow: BuildingClaimDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
