// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, SumTypeVariant } from '@clockworklabs/spacetimedb-sdk'
// A namespace for generated variants and helper functions.
export namespace BuildingInteractionLevel {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type None = { tag: 'None' }
  export type Claim = { tag: 'Claim' }
  export type Empire = { tag: 'Empire' }
  export type All = { tag: 'All' }

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const None = { tag: 'None' }
  export const Claim = { tag: 'Claim' }
  export const Empire = { tag: 'Empire' }
  export const All = { tag: 'All' }

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant('None', AlgebraicType.createProductType([])),
      new SumTypeVariant('Claim', AlgebraicType.createProductType([])),
      new SumTypeVariant('Empire', AlgebraicType.createProductType([])),
      new SumTypeVariant('All', AlgebraicType.createProductType([]))
    ])
  }

  export function serialize(writer: BinaryWriter, value: BuildingInteractionLevel): void {
    BuildingInteractionLevel.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): BuildingInteractionLevel {
    return BuildingInteractionLevel.getTypeScriptAlgebraicType().deserialize(reader)
  }
}

// The tagged union or sum type for the algebraic type `BuildingInteractionLevel`.
export type BuildingInteractionLevel =
  | BuildingInteractionLevel.None
  | BuildingInteractionLevel.Claim
  | BuildingInteractionLevel.Empire
  | BuildingInteractionLevel.All

export default BuildingInteractionLevel
