// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { OffsetCoordinatesLargeMessage as __OffsetCoordinatesLargeMessage } from './offset_coordinates_large_message_type'

export type CheatWarpRequest = {
  location: __OffsetCoordinatesLargeMessage
  ownerEntityId: bigint
}

/**
 * A namespace for generated helper functions.
 */
export namespace CheatWarpRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'location',
        __OffsetCoordinatesLargeMessage.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement('ownerEntityId', AlgebraicType.createU64Type())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: CheatWarpRequest
  ): void {
    CheatWarpRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): CheatWarpRequest {
    return CheatWarpRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
