// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'

import { PlayerClaimWithdrawFromTreasuryRequest as __PlayerClaimWithdrawFromTreasuryRequest } from './player_claim_withdraw_from_treasury_request_type'

export type ClaimWithdrawFromTreasury = {
  request: __PlayerClaimWithdrawFromTreasuryRequest
}

/**
 * A namespace for generated helper functions.
 */
export namespace ClaimWithdrawFromTreasury {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'request',
        __PlayerClaimWithdrawFromTreasuryRequest.getTypeScriptAlgebraicType()
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: ClaimWithdrawFromTreasury
  ): void {
    ClaimWithdrawFromTreasury.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(reader: BinaryReader): ClaimWithdrawFromTreasury {
    return ClaimWithdrawFromTreasury.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
