// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { ExperienceStackF32 as __ExperienceStackF32 } from './experience_stack_f_32_type'
import { ItemStack as __ItemStack } from './item_stack_type'
import { LevelRequirement as __LevelRequirement } from './level_requirement_type'
import { ToolRequirement as __ToolRequirement } from './tool_requirement_type'

export type DeconstructionRecipeDesc = {
  id: number
  timeRequirement: number
  consumedBuilding: number
  levelRequirements: __LevelRequirement[]
  toolRequirements: __ToolRequirement[]
  outputItemStacks: __ItemStack[]
  outputCargoId: number
  experiencePerProgress: __ExperienceStackF32[]
  toolMeshIndex: number
  recipePerformanceId: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace DeconstructionRecipeDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('id', AlgebraicType.createI32Type()),
      new ProductTypeElement('timeRequirement', AlgebraicType.createF32Type()),
      new ProductTypeElement('consumedBuilding', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'levelRequirements',
        AlgebraicType.createArrayType(
          __LevelRequirement.getTypeScriptAlgebraicType()
        )
      ),
      new ProductTypeElement(
        'toolRequirements',
        AlgebraicType.createArrayType(
          __ToolRequirement.getTypeScriptAlgebraicType()
        )
      ),
      new ProductTypeElement(
        'outputItemStacks',
        AlgebraicType.createArrayType(__ItemStack.getTypeScriptAlgebraicType())
      ),
      new ProductTypeElement('outputCargoId', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'experiencePerProgress',
        AlgebraicType.createArrayType(
          __ExperienceStackF32.getTypeScriptAlgebraicType()
        )
      ),
      new ProductTypeElement('toolMeshIndex', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'recipePerformanceId',
        AlgebraicType.createI32Type()
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: DeconstructionRecipeDesc
  ): void {
    DeconstructionRecipeDesc.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(reader: BinaryReader): DeconstructionRecipeDesc {
    return DeconstructionRecipeDesc.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
