// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { DroppedInventoryOwnershipTimer } from './dropped_inventory_ownership_timer_type'

/**
 * Table handle for the table `dropped_inventory_ownership_timer`.
 *
 * Obtain a handle from the [`droppedInventoryOwnershipTimer`] property on [`RemoteTables`],
 * like `ctx.db.droppedInventoryOwnershipTimer`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.droppedInventoryOwnershipTimer.on_insert(...)`.
 */
export class DroppedInventoryOwnershipTimerTableHandle {
  tableCache: TableCache<DroppedInventoryOwnershipTimer>

  constructor(tableCache: TableCache<DroppedInventoryOwnershipTimer>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<DroppedInventoryOwnershipTimer> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `scheduledId` unique index on the table `dropped_inventory_ownership_timer`,
   * which allows point queries on the field of the same name
   * via the [`DroppedInventoryOwnershipTimerScheduledIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.droppedInventoryOwnershipTimer.scheduledId().find(...)`.
   *
   * Get a handle on the `scheduledId` unique index on the table `dropped_inventory_ownership_timer`.
   */
  scheduledId = {
    // Find the subscribed row whose `scheduledId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): DroppedInventoryOwnershipTimer | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.scheduledId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: DroppedInventoryOwnershipTimer) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: DroppedInventoryOwnershipTimer) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: DroppedInventoryOwnershipTimer) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: DroppedInventoryOwnershipTimer) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (ctx: EventContext, oldRow: DroppedInventoryOwnershipTimer, newRow: DroppedInventoryOwnershipTimer) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (ctx: EventContext, onRow: DroppedInventoryOwnershipTimer, newRow: DroppedInventoryOwnershipTimer) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
