// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type DuelState = {
  entityId: bigint
  initiatorEntityId: bigint
  acceptorEntityId: bigint
  victor: bigint | undefined
  playerEntityIds: bigint[]
  outOfRangeTimestamps: (Timestamp | undefined)[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace DuelState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('initiatorEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('acceptorEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('victor', AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement('playerEntityIds', AlgebraicType.createArrayType(AlgebraicType.createU64Type())),
      new ProductTypeElement(
        'outOfRangeTimestamps',
        AlgebraicType.createArrayType(AlgebraicType.createOptionType(AlgebraicType.createTimestampType()))
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: DuelState): void {
    DuelState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): DuelState {
    return DuelState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
