// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
export type ElevatorDesc = {
  buildingId: number
  maxCliffHeight: number
  speed: number
  usableWithDeployable: boolean
  topPlatformAddress: string
  basketAddress: string
  bottomPlatformAddress: string
}

/**
 * A namespace for generated helper functions.
 */
export namespace ElevatorDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('buildingId', AlgebraicType.createI32Type()),
      new ProductTypeElement('maxCliffHeight', AlgebraicType.createU32Type()),
      new ProductTypeElement('speed', AlgebraicType.createF32Type()),
      new ProductTypeElement(
        'usableWithDeployable',
        AlgebraicType.createBoolType()
      ),
      new ProductTypeElement(
        'topPlatformAddress',
        AlgebraicType.createStringType()
      ),
      new ProductTypeElement('basketAddress', AlgebraicType.createStringType()),
      new ProductTypeElement(
        'bottomPlatformAddress',
        AlgebraicType.createStringType()
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: ElevatorDesc): void {
    ElevatorDesc.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ElevatorDesc {
    return ElevatorDesc.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
