// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { EmpireNotificationType as __EmpireNotificationType } from './empire_notification_type_type'

export type EmpireNotificationState = {
  entityId: bigint
  empireEntityId: bigint
  notificationType: __EmpireNotificationType
  textReplacement: string[]
  timestamp: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireNotificationState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('empireEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('notificationType', __EmpireNotificationType.getTypeScriptAlgebraicType()),
      new ProductTypeElement('textReplacement', AlgebraicType.createArrayType(AlgebraicType.createStringType())),
      new ProductTypeElement('timestamp', AlgebraicType.createI32Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: EmpireNotificationState): void {
    EmpireNotificationState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireNotificationState {
    return EmpireNotificationState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
