// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
export type EmpireClaimJoinMsg = {
  playerEntityId: bigint
  claimEntityId: bigint
  claimBuildingEntityId: bigint
  empireEntityId: bigint
  claimName: string
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireClaimJoinMsg {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('playerEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('claimEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'claimBuildingEntityId',
        AlgebraicType.createU64Type()
      ),
      new ProductTypeElement('empireEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('claimName', AlgebraicType.createStringType())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: EmpireClaimJoinMsg
  ): void {
    EmpireClaimJoinMsg.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireClaimJoinMsg {
    return EmpireClaimJoinMsg.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
