// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
export type EmpireDonateShardsRequest = {
  amount: number
  onBehalfUsername: string | undefined
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireDonateShardsRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('amount', AlgebraicType.createU32Type()),
      new ProductTypeElement('onBehalfUsername', AlgebraicType.createOptionType(AlgebraicType.createStringType()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: EmpireDonateShardsRequest): void {
    EmpireDonateShardsRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireDonateShardsRequest {
    return EmpireDonateShardsRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
