// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
export type EmpireUpdatePermissionsRequest = {
  empireEntityId: bigint
  rank: number
  permissions: boolean[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireUpdatePermissionsRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('empireEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('rank', AlgebraicType.createU8Type()),
      new ProductTypeElement('permissions', AlgebraicType.createArrayType(AlgebraicType.createBoolType()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: EmpireUpdatePermissionsRequest): void {
    EmpireUpdatePermissionsRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireUpdatePermissionsRequest {
    return EmpireUpdatePermissionsRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
