// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
export type EmpireMarkForExpansionRequest = {
  empireEntityId: bigint
  chunkIndex: bigint
  enabled: boolean
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireMarkForExpansionRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('empireEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('chunkIndex', AlgebraicType.createU64Type()),
      new ProductTypeElement('enabled', AlgebraicType.createBoolType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: EmpireMarkForExpansionRequest): void {
    EmpireMarkForExpansionRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireMarkForExpansionRequest {
    return EmpireMarkForExpansionRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
