// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type EmpireFoundryState = {
  entityId: bigint
  empireEntityId: bigint
  hexiteCapsules: number
  queued: number
  started: Timestamp
}

/**
 * A namespace for generated helper functions.
 */
export namespace EmpireFoundryState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('empireEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('hexiteCapsules', AlgebraicType.createI32Type()),
      new ProductTypeElement('queued', AlgebraicType.createI32Type()),
      new ProductTypeElement('started', AlgebraicType.createTimestampType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: EmpireFoundryState): void {
    EmpireFoundryState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EmpireFoundryState {
    return EmpireFoundryState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
