// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { EnemyAiParamsDesc } from './enemy_ai_params_desc_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `enemy_ai_params_desc`.
 *
 * Obtain a handle from the [`enemyAiParamsDesc`] property on [`RemoteTables`],
 * like `ctx.db.enemyAiParamsDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.enemyAiParamsDesc.on_insert(...)`.
 */
export class EnemyAiParamsDescTableHandle {
  tableCache: TableCache<EnemyAiParamsDesc>

  constructor(tableCache: TableCache<EnemyAiParamsDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<EnemyAiParamsDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `id` unique index on the table `enemy_ai_params_desc`,
   * which allows point queries on the field of the same name
   * via the [`EnemyAiParamsDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.enemyAiParamsDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `enemy_ai_params_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): EnemyAiParamsDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: EnemyAiParamsDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (
    cb: (ctx: EventContext, row: EnemyAiParamsDesc) => void
  ) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: EnemyAiParamsDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (
    cb: (ctx: EventContext, row: EnemyAiParamsDesc) => void
  ) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (
      ctx: EventContext,
      oldRow: EnemyAiParamsDesc,
      newRow: EnemyAiParamsDesc
    ) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (
      ctx: EventContext,
      onRow: EnemyAiParamsDesc,
      newRow: EnemyAiParamsDesc
    ) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
