// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { EnemyType as __EnemyType } from './enemy_type_type'
import { OffsetCoordinatesSmallMessage as __OffsetCoordinatesSmallMessage } from './offset_coordinates_small_message_type'

export type EnemyMobMonitorState = {
  entityId: bigint
  enemyType: __EnemyType
  herdEntityId: bigint
  herdLocation: __OffsetCoordinatesSmallMessage
}

/**
 * A namespace for generated helper functions.
 */
export namespace EnemyMobMonitorState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'enemyType',
        __EnemyType.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement('herdEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'herdLocation',
        __OffsetCoordinatesSmallMessage.getTypeScriptAlgebraicType()
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: EnemyMobMonitorState
  ): void {
    EnemyMobMonitorState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EnemyMobMonitorState {
    return EnemyMobMonitorState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
