// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
import { EnemyStatus as __EnemyStatus } from './enemy_status_type'
import { EnemyType as __EnemyType } from './enemy_type_type'

export type EnemyState = {
  entityId: bigint
  herdEntityId: bigint
  direction: number
  status: __EnemyStatus
  lastRangedAttackTimestamp: Timestamp
  enemyType: __EnemyType
}

/**
 * A namespace for generated helper functions.
 */
export namespace EnemyState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('herdEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('direction', AlgebraicType.createI32Type()),
      new ProductTypeElement('status', __EnemyStatus.getTypeScriptAlgebraicType()),
      new ProductTypeElement('lastRangedAttackTimestamp', AlgebraicType.createTimestampType()),
      new ProductTypeElement('enemyType', __EnemyType.getTypeScriptAlgebraicType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: EnemyState): void {
    EnemyState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EnemyState {
    return EnemyState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
