// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { EquipmentSlotType as __EquipmentSlotType } from './equipment_slot_type_type'
import { ItemStack as __ItemStack } from './item_stack_type'

export type EquipmentSlot = {
  item: __ItemStack | undefined
  primary: __EquipmentSlotType
}

/**
 * A namespace for generated helper functions.
 */
export namespace EquipmentSlot {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'item',
        AlgebraicType.createOptionType(__ItemStack.getTypeScriptAlgebraicType())
      ),
      new ProductTypeElement(
        'primary',
        __EquipmentSlotType.getTypeScriptAlgebraicType()
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: EquipmentSlot): void {
    EquipmentSlot.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): EquipmentSlot {
    return EquipmentSlot.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
