// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { FootprintType as __FootprintType } from './footprint_type_type'

export type FootprintTile = {
  x: number
  z: number
  footprintType: __FootprintType
}

/**
 * A namespace for generated helper functions.
 */
export namespace FootprintTile {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('x', AlgebraicType.createI32Type()),
      new ProductTypeElement('z', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'footprintType',
        __FootprintType.getTypeScriptAlgebraicType()
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: FootprintTile): void {
    FootprintTile.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): FootprintTile {
    return FootprintTile.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
