// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { FootprintType as __FootprintType } from './footprint_type_type'

export type FootprintTileState = {
  entityId: bigint
  ownerEntityId: bigint
  footprintType: __FootprintType
}

/**
 * A namespace for generated helper functions.
 */
export namespace FootprintTileState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('ownerEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('footprintType', __FootprintType.getTypeScriptAlgebraicType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: FootprintTileState): void {
    FootprintTileState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): FootprintTileState {
    return FootprintTileState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
