// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache } from '@clockworklabs/spacetimedb-sdk'
import { ForceGenerateTypes } from './force_generate_types_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `force_generate_types`.
 *
 * Obtain a handle from the [`forceGenerateTypes`] property on [`RemoteTables`],
 * like `ctx.db.forceGenerateTypes`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.forceGenerateTypes.on_insert(...)`.
 */
export class ForceGenerateTypesTableHandle {
  tableCache: TableCache<ForceGenerateTypes>

  constructor(tableCache: TableCache<ForceGenerateTypes>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<ForceGenerateTypes> {
    return this.tableCache.iter()
  }

  onInsert = (cb: (ctx: EventContext, row: ForceGenerateTypes) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (
    cb: (ctx: EventContext, row: ForceGenerateTypes) => void
  ) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: ForceGenerateTypes) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (
    cb: (ctx: EventContext, row: ForceGenerateTypes) => void
  ) => {
    return this.tableCache.removeOnDelete(cb)
  }
}
