// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { GateDesc } from './gate_desc_type'

/**
 * Table handle for the table `gate_desc`.
 *
 * Obtain a handle from the [`gateDesc`] property on [`RemoteTables`],
 * like `ctx.db.gateDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.gateDesc.on_insert(...)`.
 */
export class GateDescTableHandle {
  tableCache: TableCache<GateDesc>

  constructor(tableCache: TableCache<GateDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<GateDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `buildingId` unique index on the table `gate_desc`,
   * which allows point queries on the field of the same name
   * via the [`GateDescBuildingIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.gateDesc.buildingId().find(...)`.
   *
   * Get a handle on the `buildingId` unique index on the table `gate_desc`.
   */
  buildingId = {
    // Find the subscribed row whose `buildingId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): GateDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.buildingId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: GateDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: GateDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: GateDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: GateDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: GateDesc, newRow: GateDesc) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: GateDesc, newRow: GateDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
