// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { Globals } from './globals_type'

/**
 * Table handle for the table `globals`.
 *
 * Obtain a handle from the [`globals`] property on [`RemoteTables`],
 * like `ctx.db.globals`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.globals.on_insert(...)`.
 */
export class GlobalsTableHandle {
  tableCache: TableCache<Globals>

  constructor(tableCache: TableCache<Globals>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<Globals> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `version` unique index on the table `globals`,
   * which allows point queries on the field of the same name
   * via the [`GlobalsVersionUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.globals.version().find(...)`.
   *
   * Get a handle on the `version` unique index on the table `globals`.
   */
  version = {
    // Find the subscribed row whose `version` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): Globals | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.version, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: Globals) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: Globals) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: Globals) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: Globals) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (ctx: EventContext, oldRow: Globals, newRow: Globals) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (ctx: EventContext, onRow: Globals, newRow: Globals) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
