// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type GlobalSearchState = {
  entityId: bigint
  foundEntityId: bigint
  foundEntityName: string
  x: number
  z: number
  timestamp: Timestamp
}

/**
 * A namespace for generated helper functions.
 */
export namespace GlobalSearchState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('foundEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'foundEntityName',
        AlgebraicType.createStringType()
      ),
      new ProductTypeElement('x', AlgebraicType.createI32Type()),
      new ProductTypeElement('z', AlgebraicType.createI32Type()),
      new ProductTypeElement('timestamp', AlgebraicType.createTimestampType())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: GlobalSearchState
  ): void {
    GlobalSearchState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): GlobalSearchState {
    return GlobalSearchState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
