// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { EnemyAiParamsDesc as __EnemyAiParamsDesc } from './enemy_ai_params_desc_type'

export type ImportEnemyAiParamsDesc = {
  records: __EnemyAiParamsDesc[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ImportEnemyAiParamsDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('records', AlgebraicType.createArrayType(__EnemyAiParamsDesc.getTypeScriptAlgebraicType()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: ImportEnemyAiParamsDesc): void {
    ImportEnemyAiParamsDesc.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ImportEnemyAiParamsDesc {
    return ImportEnemyAiParamsDesc.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
