// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'

import { KnowledgeAchievementState as __KnowledgeAchievementState } from './knowledge_achievement_state_type'

export type ImportKnowledgeAchievementState = {
  records: __KnowledgeAchievementState[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ImportKnowledgeAchievementState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'records',
        AlgebraicType.createArrayType(
          __KnowledgeAchievementState.getTypeScriptAlgebraicType()
        )
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: ImportKnowledgeAchievementState
  ): void {
    ImportKnowledgeAchievementState.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(
    reader: BinaryReader
  ): ImportKnowledgeAchievementState {
    return ImportKnowledgeAchievementState.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
