// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'

import { UserState as __UserState } from './user_state_type'

export type ImportUserState = {
  records: __UserState[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ImportUserState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'records',
        AlgebraicType.createArrayType(__UserState.getTypeScriptAlgebraicType())
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: ImportUserState
  ): void {
    ImportUserState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ImportUserState {
    return ImportUserState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
