// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { RegionSignInParameters as __RegionSignInParameters } from './region_sign_in_parameters_type'

export type ImportRegionSignInParameters = {
  records: __RegionSignInParameters[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ImportRegionSignInParameters {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'records',
        AlgebraicType.createArrayType(__RegionSignInParameters.getTypeScriptAlgebraicType())
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: ImportRegionSignInParameters): void {
    ImportRegionSignInParameters.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ImportRegionSignInParameters {
    return ImportRegionSignInParameters.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
