// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { AdminBroadcast as __AdminBroadcast } from './admin_broadcast_type'

export type ImportAdminBroadcast = {
  records: __AdminBroadcast[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ImportAdminBroadcast {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('records', AlgebraicType.createArrayType(__AdminBroadcast.getTypeScriptAlgebraicType()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: ImportAdminBroadcast): void {
    ImportAdminBroadcast.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ImportAdminBroadcast {
    return ImportAdminBroadcast.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
