// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { ItemType as __ItemType } from './item_type_type'

export type InputItemStack = {
  itemId: number
  quantity: number
  itemType: __ItemType
  discoveryScore: number
  consumptionChance: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace InputItemStack {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('itemId', AlgebraicType.createI32Type()),
      new ProductTypeElement('quantity', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'itemType',
        __ItemType.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement('discoveryScore', AlgebraicType.createI32Type()),
      new ProductTypeElement('consumptionChance', AlgebraicType.createF32Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: InputItemStack): void {
    InputItemStack.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): InputItemStack {
    return InputItemStack.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
