// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { TerrainChunkState as __TerrainChunkState } from './terrain_chunk_state_type'
import { WorldGenGeneratedBuilding as __WorldGenGeneratedBuilding } from './world_gen_generated_building_type'
import { WorldGenGeneratedResourceDeposit as __WorldGenGeneratedResourceDeposit } from './world_gen_generated_resource_deposit_type'

export type InsertTerrainChunk = {
  terrainChunk: __TerrainChunkState
  buildings: __WorldGenGeneratedBuilding[]
  resources: __WorldGenGeneratedResourceDeposit[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace InsertTerrainChunk {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('terrainChunk', __TerrainChunkState.getTypeScriptAlgebraicType()),
      new ProductTypeElement(
        'buildings',
        AlgebraicType.createArrayType(__WorldGenGeneratedBuilding.getTypeScriptAlgebraicType())
      ),
      new ProductTypeElement(
        'resources',
        AlgebraicType.createArrayType(__WorldGenGeneratedResourceDeposit.getTypeScriptAlgebraicType())
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: InsertTerrainChunk): void {
    InsertTerrainChunk.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): InsertTerrainChunk {
    return InsertTerrainChunk.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
