// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { MessageContents as __MessageContents } from './message_contents_type'

export type InterModuleMessage = {
  id: bigint
  to: number
  contents: __MessageContents
}

/**
 * A namespace for generated helper functions.
 */
export namespace InterModuleMessage {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('id', AlgebraicType.createU64Type()),
      new ProductTypeElement('to', AlgebraicType.createU8Type()),
      new ProductTypeElement('contents', __MessageContents.getTypeScriptAlgebraicType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: InterModuleMessage): void {
    InterModuleMessage.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): InterModuleMessage {
    return InterModuleMessage.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
