// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'

import { PlayerDroppedInventoryPickUpRequest as __PlayerDroppedInventoryPickUpRequest } from './player_dropped_inventory_pick_up_request_type'

export type ItemPickUp = {
  request: __PlayerDroppedInventoryPickUpRequest
}

/**
 * A namespace for generated helper functions.
 */
export namespace ItemPickUp {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('request', __PlayerDroppedInventoryPickUpRequest.getTypeScriptAlgebraicType())
    ])
  }

  export function serialize(writer: BinaryWriter, value: ItemPickUp): void {
    ItemPickUp.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ItemPickUp {
    return ItemPickUp.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
