// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { ItemListPossibility as __ItemListPossibility } from './item_list_possibility_type'

export type ItemListDesc = {
  id: number
  name: string
  possibilities: __ItemListPossibility[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace ItemListDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('id', AlgebraicType.createI32Type()),
      new ProductTypeElement('name', AlgebraicType.createStringType()),
      new ProductTypeElement(
        'possibilities',
        AlgebraicType.createArrayType(__ItemListPossibility.getTypeScriptAlgebraicType())
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: ItemListDesc): void {
    ItemListDesc.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ItemListDesc {
    return ItemListDesc.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
