// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { KnowledgeLocationEntry as __KnowledgeLocationEntry } from './knowledge_location_entry_type'

export type KnowledgeRuinsState = {
  entityId: bigint
  entries: __KnowledgeLocationEntry[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace KnowledgeRuinsState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'entries',
        AlgebraicType.createArrayType(
          __KnowledgeLocationEntry.getTypeScriptAlgebraicType()
        )
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: KnowledgeRuinsState
  ): void {
    KnowledgeRuinsState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): KnowledgeRuinsState {
    return KnowledgeRuinsState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
