// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { KnowledgeLoreState } from './knowledge_lore_state_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `knowledge_lore_state`.
 *
 * Obtain a handle from the [`knowledgeLoreState`] property on [`RemoteTables`],
 * like `ctx.db.knowledgeLoreState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.knowledgeLoreState.on_insert(...)`.
 */
export class KnowledgeLoreStateTableHandle {
  tableCache: TableCache<KnowledgeLoreState>

  constructor(tableCache: TableCache<KnowledgeLoreState>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<KnowledgeLoreState> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `entityId` unique index on the table `knowledge_lore_state`,
   * which allows point queries on the field of the same name
   * via the [`KnowledgeLoreStateEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.knowledgeLoreState.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `knowledge_lore_state`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): KnowledgeLoreState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: KnowledgeLoreState) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: KnowledgeLoreState) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: KnowledgeLoreState) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: KnowledgeLoreState) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: KnowledgeLoreState, newRow: KnowledgeLoreState) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: KnowledgeLoreState, newRow: KnowledgeLoreState) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
