// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { CsvStatEntry as __CsvStatEntry } from './csv_stat_entry_type'

export type KnowledgeStatModifierDesc = {
  secondaryKnowledgeId: number
  stats: __CsvStatEntry[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace KnowledgeStatModifierDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'secondaryKnowledgeId',
        AlgebraicType.createI32Type()
      ),
      new ProductTypeElement(
        'stats',
        AlgebraicType.createArrayType(
          __CsvStatEntry.getTypeScriptAlgebraicType()
        )
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: KnowledgeStatModifierDesc
  ): void {
    KnowledgeStatModifierDesc.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(reader: BinaryReader): KnowledgeStatModifierDesc {
    return KnowledgeStatModifierDesc.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
