// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  TimeDuration,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type LootChestDespawnTimer = {
  scheduledId: bigint
  scheduledAt:
    | { tag: 'Interval'; value: TimeDuration }
    | { tag: 'Time'; value: Timestamp }
  lootChestEntityId: bigint
  shouldRespawn: boolean
}

/**
 * A namespace for generated helper functions.
 */
export namespace LootChestDespawnTimer {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('scheduledId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'scheduledAt',
        AlgebraicType.createScheduleAtType()
      ),
      new ProductTypeElement(
        'lootChestEntityId',
        AlgebraicType.createU64Type()
      ),
      new ProductTypeElement('shouldRespawn', AlgebraicType.createBoolType())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: LootChestDespawnTimer
  ): void {
    LootChestDespawnTimer.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): LootChestDespawnTimer {
    return LootChestDespawnTimer.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
