// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { LostItemsState } from './lost_items_state_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `lost_items_state`.
 *
 * Obtain a handle from the [`lostItemsState`] property on [`RemoteTables`],
 * like `ctx.db.lostItemsState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.lostItemsState.on_insert(...)`.
 */
export class LostItemsStateTableHandle {
  tableCache: TableCache<LostItemsState>

  constructor(tableCache: TableCache<LostItemsState>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<LostItemsState> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `inventoryEntityId` unique index on the table `lost_items_state`,
   * which allows point queries on the field of the same name
   * via the [`LostItemsStateInventoryEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.lostItemsState.inventoryEntityId().find(...)`.
   *
   * Get a handle on the `inventoryEntityId` unique index on the table `lost_items_state`.
   */
  inventoryEntityId = {
    // Find the subscribed row whose `inventoryEntityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): LostItemsState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.inventoryEntityId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: LostItemsState) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: LostItemsState) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: LostItemsState) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: LostItemsState) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (
      ctx: EventContext,
      oldRow: LostItemsState,
      newRow: LostItemsState
    ) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (
      ctx: EventContext,
      onRow: LostItemsState,
      newRow: LostItemsState
    ) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
