// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type MoveValidationStrikeCounterState = {
  entityId: bigint
  validationFailureTimestamps: Timestamp[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace MoveValidationStrikeCounterState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'validationFailureTimestamps',
        AlgebraicType.createArrayType(AlgebraicType.createTimestampType())
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: MoveValidationStrikeCounterState
  ): void {
    MoveValidationStrikeCounterState.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(
    reader: BinaryReader
  ): MoveValidationStrikeCounterState {
    return MoveValidationStrikeCounterState.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
