// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { NpcDesc } from './npc_desc_type'

/**
 * Table handle for the table `npc_desc`.
 *
 * Obtain a handle from the [`npcDesc`] property on [`RemoteTables`],
 * like `ctx.db.npcDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.npcDesc.on_insert(...)`.
 */
export class NpcDescTableHandle {
  tableCache: TableCache<NpcDesc>

  constructor(tableCache: TableCache<NpcDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<NpcDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `npcType` unique index on the table `npc_desc`,
   * which allows point queries on the field of the same name
   * via the [`NpcDescNpcTypeUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.npcDesc.npcType().find(...)`.
   *
   * Get a handle on the `npcType` unique index on the table `npc_desc`.
   */
  npcType = {
    // Find the subscribed row whose `npcType` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): NpcDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.npcType, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: NpcDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: NpcDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: NpcDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: NpcDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: NpcDesc, newRow: NpcDesc) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: NpcDesc, newRow: NpcDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
