// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { DeployableState as __DeployableState } from './deployable_state_type'
import { TradeOrderState as __TradeOrderState } from './trade_order_state_type'

export type OnDeployableRecoveredMsg = {
  playerEntityId: bigint
  deployableEntityId: bigint
  deployableDescId: number
  deployableState: __DeployableState
  tradeOrders: __TradeOrderState[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace OnDeployableRecoveredMsg {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('playerEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'deployableEntityId',
        AlgebraicType.createU64Type()
      ),
      new ProductTypeElement('deployableDescId', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'deployableState',
        __DeployableState.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement(
        'tradeOrders',
        AlgebraicType.createArrayType(
          __TradeOrderState.getTypeScriptAlgebraicType()
        )
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: OnDeployableRecoveredMsg
  ): void {
    OnDeployableRecoveredMsg.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(reader: BinaryReader): OnDeployableRecoveredMsg {
    return OnDeployableRecoveredMsg.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
