// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
import { PassiveCraftStatus as __PassiveCraftStatus } from './passive_craft_status_type'

export type PassiveCraftState = {
  entityId: bigint
  ownerEntityId: bigint
  recipeId: number
  buildingEntityId: bigint
  timestamp: Timestamp
  status: __PassiveCraftStatus
  slot: number | undefined
}

/**
 * A namespace for generated helper functions.
 */
export namespace PassiveCraftState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('ownerEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('recipeId', AlgebraicType.createI32Type()),
      new ProductTypeElement('buildingEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('timestamp', AlgebraicType.createTimestampType()),
      new ProductTypeElement(
        'status',
        __PassiveCraftStatus.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement(
        'slot',
        AlgebraicType.createOptionType(AlgebraicType.createU32Type())
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: PassiveCraftState
  ): void {
    PassiveCraftState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PassiveCraftState {
    return PassiveCraftState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
