// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { OffsetCoordinatesSmallMessage as __OffsetCoordinatesSmallMessage } from './offset_coordinates_small_message_type'

export type PlayerBuildingMoveRequest = {
  buildingEntityId: bigint
  newCoordinates: __OffsetCoordinatesSmallMessage
  facingDirection: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerBuildingMoveRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('buildingEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('newCoordinates', __OffsetCoordinatesSmallMessage.getTypeScriptAlgebraicType()),
      new ProductTypeElement('facingDirection', AlgebraicType.createI32Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: PlayerBuildingMoveRequest): void {
    PlayerBuildingMoveRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PlayerBuildingMoveRequest {
    return PlayerBuildingMoveRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
