// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { PlayerActionLayer as __PlayerActionLayer } from './player_action_layer_type'

export type PlayerActionDesc = {
  actionTypeId: number
  layer: __PlayerActionLayer
  allowedConcurrentActionIds: number[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerActionDesc {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('actionTypeId', AlgebraicType.createI32Type()),
      new ProductTypeElement('layer', __PlayerActionLayer.getTypeScriptAlgebraicType()),
      new ProductTypeElement('allowedConcurrentActionIds', AlgebraicType.createArrayType(AlgebraicType.createI32Type()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: PlayerActionDesc): void {
    PlayerActionDesc.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PlayerActionDesc {
    return PlayerActionDesc.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
