// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { PlayerQueueState } from './player_queue_state_type'

/**
 * Table handle for the table `player_queue_state`.
 *
 * Obtain a handle from the [`playerQueueState`] property on [`RemoteTables`],
 * like `ctx.db.playerQueueState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.playerQueueState.on_insert(...)`.
 */
export class PlayerQueueStateTableHandle {
  tableCache: TableCache<PlayerQueueState>

  constructor(tableCache: TableCache<PlayerQueueState>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<PlayerQueueState> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `index` unique index on the table `player_queue_state`,
   * which allows point queries on the field of the same name
   * via the [`PlayerQueueStateIndexUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.playerQueueState.index().find(...)`.
   *
   * Get a handle on the `index` unique index on the table `player_queue_state`.
   */
  index = {
    // Find the subscribed row whose `index` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PlayerQueueState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.index, col_val)) {
          return row
        }
      }
    }
  }
  /**
   * Access to the `entityId` unique index on the table `player_queue_state`,
   * which allows point queries on the field of the same name
   * via the [`PlayerQueueStateEntityIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.playerQueueState.entityId().find(...)`.
   *
   * Get a handle on the `entityId` unique index on the table `player_queue_state`.
   */
  entityId = {
    // Find the subscribed row whose `entityId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): PlayerQueueState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.entityId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: PlayerQueueState) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: PlayerQueueState) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: PlayerQueueState) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: PlayerQueueState) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (
      ctx: EventContext,
      oldRow: PlayerQueueState,
      newRow: PlayerQueueState
    ) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (
      ctx: EventContext,
      onRow: PlayerQueueState,
      newRow: PlayerQueueState
    ) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
