// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type PlayerHousingState = {
  entityId: bigint
  entranceBuildingEntityId: bigint
  networkEntityId: bigint
  exitPortalEntityId: bigint
  rank: number
  lockedUntil: Timestamp
  isEmpty: boolean
  regionIndex: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerHousingState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('entityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('entranceBuildingEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('networkEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('exitPortalEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('rank', AlgebraicType.createI32Type()),
      new ProductTypeElement('lockedUntil', AlgebraicType.createTimestampType()),
      new ProductTypeElement('isEmpty', AlgebraicType.createBoolType()),
      new ProductTypeElement('regionIndex', AlgebraicType.createU8Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: PlayerHousingState): void {
    PlayerHousingState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PlayerHousingState {
    return PlayerHousingState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
