// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { Permission as __Permission } from './permission_type'

export type PlayerPermissionEditRequest = {
  ordainedEntityId: bigint
  allowedEntityId: bigint
  permission: __Permission | undefined
}

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerPermissionEditRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('ordainedEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('allowedEntityId', AlgebraicType.createU64Type()),
      new ProductTypeElement('permission', AlgebraicType.createOptionType(__Permission.getTypeScriptAlgebraicType()))
    ])
  }

  export function serialize(writer: BinaryWriter, value: PlayerPermissionEditRequest): void {
    PlayerPermissionEditRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PlayerPermissionEditRequest {
    return PlayerPermissionEditRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
