// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { ChatChannel as __ChatChannel } from './chat_channel_type'

export type PlayerChatPostMessageRequest = {
  text: string
  channelId: __ChatChannel
  targetId: bigint
}

/**
 * A namespace for generated helper functions.
 */
export namespace PlayerChatPostMessageRequest {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('text', AlgebraicType.createStringType()),
      new ProductTypeElement('channelId', __ChatChannel.getTypeScriptAlgebraicType()),
      new ProductTypeElement('targetId', AlgebraicType.createU64Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: PlayerChatPostMessageRequest): void {
    PlayerChatPostMessageRequest.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): PlayerChatPostMessageRequest {
    return PlayerChatPostMessageRequest.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
