// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, SumTypeVariant } from '@clockworklabs/spacetimedb-sdk'
// A namespace for generated variants and helper functions.
export namespace ProgressiveActionStatus {
  // These are the generated variant types for each variant of the tagged union.
  // One type is generated per variant and will be used in the `value` field of
  // the tagged union.
  export type None = { tag: 'None' }
  export type Active = { tag: 'Active' }
  export type Suspended = { tag: 'Suspended' }
  export type Completed = { tag: 'Completed' }

  // Helper functions for constructing each variant of the tagged union.
  // ```
  // const foo = Foo.A(42);
  // assert!(foo.tag === "A");
  // assert!(foo.value === 42);
  // ```
  export const None = { tag: 'None' }
  export const Active = { tag: 'Active' }
  export const Suspended = { tag: 'Suspended' }
  export const Completed = { tag: 'Completed' }

  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createSumType([
      new SumTypeVariant('None', AlgebraicType.createProductType([])),
      new SumTypeVariant('Active', AlgebraicType.createProductType([])),
      new SumTypeVariant('Suspended', AlgebraicType.createProductType([])),
      new SumTypeVariant('Completed', AlgebraicType.createProductType([]))
    ])
  }

  export function serialize(writer: BinaryWriter, value: ProgressiveActionStatus): void {
    ProgressiveActionStatus.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): ProgressiveActionStatus {
    return ProgressiveActionStatus.getTypeScriptAlgebraicType().deserialize(reader)
  }
}

// The tagged union or sum type for the algebraic type `ProgressiveActionStatus`.
export type ProgressiveActionStatus =
  | ProgressiveActionStatus.None
  | ProgressiveActionStatus.Active
  | ProgressiveActionStatus.Suspended
  | ProgressiveActionStatus.Completed

export default ProgressiveActionStatus
