// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { ResourcesLog } from './resources_log_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `resources_log`.
 *
 * Obtain a handle from the [`resourcesLog`] property on [`RemoteTables`],
 * like `ctx.db.resourcesLog`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.resourcesLog.on_insert(...)`.
 */
export class ResourcesLogTableHandle {
  tableCache: TableCache<ResourcesLog>

  constructor(tableCache: TableCache<ResourcesLog>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<ResourcesLog> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `version` unique index on the table `resources_log`,
   * which allows point queries on the field of the same name
   * via the [`ResourcesLogVersionUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.resourcesLog.version().find(...)`.
   *
   * Get a handle on the `version` unique index on the table `resources_log`.
   */
  version = {
    // Find the subscribed row whose `version` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): ResourcesLog | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.version, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: ResourcesLog) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: ResourcesLog) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: ResourcesLog) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: ResourcesLog) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: ResourcesLog, newRow: ResourcesLog) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: ResourcesLog, newRow: ResourcesLog) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
