// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
export type TerrainCell = {
  x: number
  z: number
  dimension: number
  elevation: number
  waterLevel: number
  biomes: number
  biomeDensity: number
  originalElevation: number
  zoningType: number
  waterBodyType: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace TerrainCell {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('x', AlgebraicType.createI32Type()),
      new ProductTypeElement('z', AlgebraicType.createI32Type()),
      new ProductTypeElement('dimension', AlgebraicType.createU32Type()),
      new ProductTypeElement('elevation', AlgebraicType.createI16Type()),
      new ProductTypeElement('waterLevel', AlgebraicType.createI16Type()),
      new ProductTypeElement('biomes', AlgebraicType.createU32Type()),
      new ProductTypeElement('biomeDensity', AlgebraicType.createU32Type()),
      new ProductTypeElement('originalElevation', AlgebraicType.createI16Type()),
      new ProductTypeElement('zoningType', AlgebraicType.createU8Type()),
      new ProductTypeElement('waterBodyType', AlgebraicType.createU8Type())
    ])
  }

  export function serialize(writer: BinaryWriter, value: TerrainCell): void {
    TerrainCell.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): TerrainCell {
    return TerrainCell.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
