// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { TheGreatPlaceHolderTable } from './the_great_place_holder_table_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `the_great_placeholder_table`.
 *
 * Obtain a handle from the [`theGreatPlaceholderTable`] property on [`RemoteTables`],
 * like `ctx.db.theGreatPlaceholderTable`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.theGreatPlaceholderTable.on_insert(...)`.
 */
export class TheGreatPlaceholderTableTableHandle {
  tableCache: TableCache<TheGreatPlaceHolderTable>

  constructor(tableCache: TableCache<TheGreatPlaceHolderTable>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<TheGreatPlaceHolderTable> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `placeholderId` unique index on the table `the_great_placeholder_table`,
   * which allows point queries on the field of the same name
   * via the [`TheGreatPlaceholderTablePlaceholderIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.theGreatPlaceholderTable.placeholderId().find(...)`.
   *
   * Get a handle on the `placeholderId` unique index on the table `the_great_placeholder_table`.
   */
  placeholderId = {
    // Find the subscribed row whose `placeholderId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): TheGreatPlaceHolderTable | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.placeholderId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: TheGreatPlaceHolderTable) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: TheGreatPlaceHolderTable) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: TheGreatPlaceHolderTable) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: TheGreatPlaceHolderTable) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: TheGreatPlaceHolderTable, newRow: TheGreatPlaceHolderTable) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (ctx: EventContext, onRow: TheGreatPlaceHolderTable, newRow: TheGreatPlaceHolderTable) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
