// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement,
  TimeDuration,
  Timestamp
} from '@clockworklabs/spacetimedb-sdk'
export type TravelerTaskLoopTimer = {
  scheduledId: bigint
  scheduledAt:
    | { tag: 'Interval'; value: TimeDuration }
    | { tag: 'Time'; value: Timestamp }
}

/**
 * A namespace for generated helper functions.
 */
export namespace TravelerTaskLoopTimer {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('scheduledId', AlgebraicType.createU64Type()),
      new ProductTypeElement(
        'scheduledAt',
        AlgebraicType.createScheduleAtType()
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: TravelerTaskLoopTimer
  ): void {
    TravelerTaskLoopTimer.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): TravelerTaskLoopTimer {
    return TravelerTaskLoopTimer.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
