// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { TravelerTaskDesc } from './traveler_task_desc_type'

import { type EventContext } from '.'

/**
 * Table handle for the table `traveler_task_desc`.
 *
 * Obtain a handle from the [`travelerTaskDesc`] property on [`RemoteTables`],
 * like `ctx.db.travelerTaskDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.travelerTaskDesc.on_insert(...)`.
 */
export class TravelerTaskDescTableHandle {
  tableCache: TableCache<TravelerTaskDesc>

  constructor(tableCache: TableCache<TravelerTaskDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<TravelerTaskDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `id` unique index on the table `traveler_task_desc`,
   * which allows point queries on the field of the same name
   * via the [`TravelerTaskDescIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.travelerTaskDesc.id().find(...)`.
   *
   * Get a handle on the `id` unique index on the table `traveler_task_desc`.
   */
  id = {
    // Find the subscribed row whose `id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): TravelerTaskDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.id, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: TravelerTaskDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: TravelerTaskDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: TravelerTaskDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: TravelerTaskDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: TravelerTaskDesc, newRow: TravelerTaskDesc) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: TravelerTaskDesc, newRow: TravelerTaskDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
