// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Identity, TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { UnclaimedCollectiblesState } from './unclaimed_collectibles_state_type'

/**
 * Table handle for the table `unclaimed_collectibles_state`.
 *
 * Obtain a handle from the [`unclaimedCollectiblesState`] property on [`RemoteTables`],
 * like `ctx.db.unclaimedCollectiblesState`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.unclaimedCollectiblesState.on_insert(...)`.
 */
export class UnclaimedCollectiblesStateTableHandle {
  tableCache: TableCache<UnclaimedCollectiblesState>

  constructor(tableCache: TableCache<UnclaimedCollectiblesState>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<UnclaimedCollectiblesState> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `identity` unique index on the table `unclaimed_collectibles_state`,
   * which allows point queries on the field of the same name
   * via the [`UnclaimedCollectiblesStateIdentityUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.unclaimedCollectiblesState.identity().find(...)`.
   *
   * Get a handle on the `identity` unique index on the table `unclaimed_collectibles_state`.
   */
  identity = {
    // Find the subscribed row whose `identity` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: Identity): UnclaimedCollectiblesState | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.identity, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: UnclaimedCollectiblesState) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: UnclaimedCollectiblesState) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: UnclaimedCollectiblesState) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: UnclaimedCollectiblesState) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (
    cb: (ctx: EventContext, oldRow: UnclaimedCollectiblesState, newRow: UnclaimedCollectiblesState) => void
  ) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (
    cb: (ctx: EventContext, onRow: UnclaimedCollectiblesState, newRow: UnclaimedCollectiblesState) => void
  ) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
