// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  Identity,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
export type UnclaimedCollectiblesState = {
  identity: Identity
  collectibles: number[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace UnclaimedCollectiblesState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('identity', AlgebraicType.createIdentityType()),
      new ProductTypeElement(
        'collectibles',
        AlgebraicType.createArrayType(AlgebraicType.createI32Type())
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: UnclaimedCollectiblesState
  ): void {
    UnclaimedCollectiblesState.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(
    reader: BinaryReader
  ): UnclaimedCollectiblesState {
    return UnclaimedCollectiblesState.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
