// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { TableCache, deepEqual } from '@clockworklabs/spacetimedb-sdk'
import { type EventContext } from '.'
import { WeaponDesc } from './weapon_desc_type'

/**
 * Table handle for the table `weapon_desc`.
 *
 * Obtain a handle from the [`weaponDesc`] property on [`RemoteTables`],
 * like `ctx.db.weaponDesc`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.weaponDesc.on_insert(...)`.
 */
export class WeaponDescTableHandle {
  tableCache: TableCache<WeaponDesc>

  constructor(tableCache: TableCache<WeaponDesc>) {
    this.tableCache = tableCache
  }

  count(): number {
    return this.tableCache.count()
  }

  iter(): Iterable<WeaponDesc> {
    return this.tableCache.iter()
  }
  /**
   * Access to the `itemId` unique index on the table `weapon_desc`,
   * which allows point queries on the field of the same name
   * via the [`WeaponDescItemIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.weaponDesc.itemId().find(...)`.
   *
   * Get a handle on the `itemId` unique index on the table `weapon_desc`.
   */
  itemId = {
    // Find the subscribed row whose `itemId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: number): WeaponDesc | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.itemId, col_val)) {
          return row
        }
      }
    }
  }

  onInsert = (cb: (ctx: EventContext, row: WeaponDesc) => void) => {
    return this.tableCache.onInsert(cb)
  }

  removeOnInsert = (cb: (ctx: EventContext, row: WeaponDesc) => void) => {
    return this.tableCache.removeOnInsert(cb)
  }

  onDelete = (cb: (ctx: EventContext, row: WeaponDesc) => void) => {
    return this.tableCache.onDelete(cb)
  }

  removeOnDelete = (cb: (ctx: EventContext, row: WeaponDesc) => void) => {
    return this.tableCache.removeOnDelete(cb)
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: WeaponDesc, newRow: WeaponDesc) => void) => {
    return this.tableCache.onUpdate(cb)
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: WeaponDesc, newRow: WeaponDesc) => void) => {
    return this.tableCache.removeOnUpdate(cb)
  }
}
