// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { AlgebraicType, BinaryReader, BinaryWriter, ProductTypeElement } from '@clockworklabs/spacetimedb-sdk'
import { WorldGenResourceDefinition as __WorldGenResourceDefinition } from './world_gen_resource_definition_type'

export type WorldGenResourcesMapDefinition = {
  seed: number
  resources: __WorldGenResourceDefinition[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenResourcesMapDefinition {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('seed', AlgebraicType.createI32Type()),
      new ProductTypeElement(
        'resources',
        AlgebraicType.createArrayType(__WorldGenResourceDefinition.getTypeScriptAlgebraicType())
      )
    ])
  }

  export function serialize(writer: BinaryWriter, value: WorldGenResourcesMapDefinition): void {
    WorldGenResourcesMapDefinition.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): WorldGenResourcesMapDefinition {
    return WorldGenResourcesMapDefinition.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
