// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
export type WorldRegionState = {
  id: number
  regionMinChunkX: number
  regionMinChunkZ: number
  regionWidthChunks: number
  regionHeightChunks: number
  regionIndex: number
  regionCount: number
  regionCountSqrt: number
}

/**
 * A namespace for generated helper functions.
 */
export namespace WorldRegionState {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement('id', AlgebraicType.createU8Type()),
      new ProductTypeElement('regionMinChunkX', AlgebraicType.createU16Type()),
      new ProductTypeElement('regionMinChunkZ', AlgebraicType.createU16Type()),
      new ProductTypeElement(
        'regionWidthChunks',
        AlgebraicType.createU16Type()
      ),
      new ProductTypeElement(
        'regionHeightChunks',
        AlgebraicType.createU16Type()
      ),
      new ProductTypeElement('regionIndex', AlgebraicType.createU8Type()),
      new ProductTypeElement('regionCount', AlgebraicType.createU8Type()),
      new ProductTypeElement('regionCountSqrt', AlgebraicType.createU8Type())
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: WorldRegionState
  ): void {
    WorldRegionState.getTypeScriptAlgebraicType().serialize(writer, value)
  }

  export function deserialize(reader: BinaryReader): WorldRegionState {
    return WorldRegionState.getTypeScriptAlgebraicType().deserialize(reader)
  }
}
