// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  BinaryReader,
  BinaryWriter,
  ProductTypeElement
} from '@clockworklabs/spacetimedb-sdk'
import { WorldGenResourceBiome as __WorldGenResourceBiome } from './world_gen_resource_biome_type'
import { WorldGenResourceDetails as __WorldGenResourceDetails } from './world_gen_resource_details_type'

export type WorldGenResourceDefinition = {
  resourceDetails: __WorldGenResourceDetails
  biomes: __WorldGenResourceBiome[]
}

/**
 * A namespace for generated helper functions.
 */
export namespace WorldGenResourceDefinition {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        'resourceDetails',
        __WorldGenResourceDetails.getTypeScriptAlgebraicType()
      ),
      new ProductTypeElement(
        'biomes',
        AlgebraicType.createArrayType(
          __WorldGenResourceBiome.getTypeScriptAlgebraicType()
        )
      )
    ])
  }

  export function serialize(
    writer: BinaryWriter,
    value: WorldGenResourceDefinition
  ): void {
    WorldGenResourceDefinition.getTypeScriptAlgebraicType().serialize(
      writer,
      value
    )
  }

  export function deserialize(
    reader: BinaryReader
  ): WorldGenResourceDefinition {
    return WorldGenResourceDefinition.getTypeScriptAlgebraicType().deserialize(
      reader
    )
  }
}
